name: Get application version
description: Run docker and necessary deps
inputs:
  app_name: 
    description: 'Name of the application'
    required: true
    default: ''
outputs:
  zigbee2mqtt:
    description: Version of Zigbee2MQTT
    value: ${{ steps.version.outputs.Z2M }}
  mosquitto:
    description: Version of Mosquitto
    value: ${{ steps.version.outputs.MOSQUITTO }}
  domoticz:
    description: Version of Domoticz
    value: ${{ steps.version.outputs.DOMOTICZ }}

runs:
  using: "composite"
  steps:
    - name: Read variables
      id: version
      shell: bash
      run: |
        echo "Z2M=$(jq -r '.zigbee2mqtt' versions.json)" >> $GITHUB_OUTPUT
        echo "MOSQUITTO=$(jq -r '.mosquitto' versions.json)" >> $GITHUB_OUTPUT
        echo "DOMOTICZ=$(jq -r '.domoticz' versions.json)" >> $GITHUB_OUTPUT