name: Build Zigbee2MQTT

on: push

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/thesis_zigbee2mqtt:${{ github.sha }}"

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  determine_version:
    runs-on: ubuntu-latest
    outputs:
      zigbee2mqtt: ${{ steps.version.outputs.Z2M_VERSION }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Read variables
      id: version
      run: |
        echo "Z2M_VERSION=$(jq -r '.zigbee2mqtt' versions.json)" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT

  fetch_code:
    runs-on: ubuntu-latest
    needs: [determine_version]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: Koenkk/zigbee2mqtt
        ref: refs/tags/${{ needs.determine_version.outputs.zigbee2mqtt }}
        fetch-depth: 1
    - uses: actions/upload-artifact@v4
      with:
        name: z2m_code
        path: ./*
  
  semgrep_sast:
    needs: ['fetch_code']
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@master
      with:
        name: z2m_code
        path: .
    - name: Scan with semgrep
      run: semgrep --config="p/nodejs" --config="p/typescript" --config="p/javascript" --error --sarif --output report.sarif --metrics=off
    - name: save report as pipeline artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: z2m_semgrep.sarif
        path: report.sarif
    
  snyk_sast:
    needs: ['fetch_code']
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@master
      with:
        name: z2m_code
        path: .
    - name: fafa
      run: ls -lah
    - uses: snyk/actions/setup@master
    - name: Run Snyk to check for vulnerabilities
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk code test --sarif-file-output=report.sarif || true
    - name: save report as pipeline artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: z2m_snyk.sarif
        path: report.sarif

  SAST_checkpoint:
    needs: 
    - semgrep_sast
    - snyk_sast
    - DAST
    runs-on: ubuntu-latest
    steps:
      - name: Download semgrep report
        uses: actions/download-artifact@master
        with:
          name: z2m_semgrep.sarif
          path: .
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: z2m_semgrep.sarig
      - name: Download snyk report
        uses: actions/download-artifact@master
        with:
          name: z2m_snyk.sarif
          path: .
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: z2m_snyk.sarig
      - name: Merge SARIFs
        uses: microsoft/sarif-actions@v0.1
        with:
          command: 'merge . --recurse true --output-file=sast_report.sarif'
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: z2m_sast_report.sarif
          path: sast_report.sarif
  
  build:
    needs: [ SAST_checkpoint ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: z2m_code
        path: .
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}
        platforms: linux/arm64/v8,linux/386,linux/amd64,linux/arm/v6,linux/arm/v7
        provenance: false
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        image: ${{ env.IMAGE_NAME }}
        format: cyclonedx-json
        output-file: sbom.json
        # artifact-name: sbom.json
    - name: save report as pipeline artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sbom.json
        path: sbom.json

  SCA:
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - name: Download SBOM
        uses: actions/download-artifact@master
        with:
          name: sbom.json
          path: .
      - run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.50.1
      - run: |
          trivy sbom sbom.json --format sarif --output sca_result.sarif
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sca_result.sarif
          path: sca_result.sarif


  DAST:
    needs: fetch_code
    runs-on: 'ubuntu-latest'
    steps:
      - run: 'echo tipa DAST'

        
        