name: Build Zigbee2MQTT

on: workflow_dispatch

env:
  Z2M_VERSION: '1.35.3'

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build_zigbee2mqtt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: Koenkk/zigbee2mqtt
        ref: refs/tags/${{ env.Z2M_VERSION }}
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # - name: "release: Docker build"
    #   run: |
    #     TAG="$(git describe --tags)"
    #     docker buildx build \
    #       --build-arg COMMIT=$(git rev-parse --short HEAD) \
    #       --platform linux/arm64/v8,linux/386,linux/amd64,linux/arm/v6,linux/arm/v7 \
    #       -f docker/Dockerfile \
    #       --provenance=false \
    #       --push \
    #       -t ghcr.io/kinjalik/thesis_zigbee2mqtt:1.35.3 \
    #       .
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/thesis_zigbee2mqtt:${{ env.Z2M_VERSION }}
        platforms: linux/arm64/v8,linux/386,linux/amd64,linux/arm/v6,linux/arm/v7
        provenance: false