name: PR Inspection of Domoticz

on: pull_request

#used for both X86 and qemu, require to rebuild the github packages via a manual workflow_dispatch
env:
  IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/thesis_domoticz"
  IMAGE_TAG: "${{ github.sha }}"
  SBOM_FILENAME: sbom.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Domoticz version
      uses: ./.github/actions/get-version
      id: version
      with:
        app_name: domoticz

    - name : Checkout Domoticz
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: true
        repository: domoticz/domoticz-docker
        path: domoticz

    - name: Build domoticz
      uses: ./.github/actions/build-domoticz
      with:
        working-directory: ./domoticz
        app_version: ${{ steps.version.outputs.value }}
        image_name: ${{ env.IMAGE_NAME }}
        image_tag: ${{ env.IMAGE_TAG }}
        sbom_filename: ${{ env.SBOM_FILENAME }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: save report as pipeline artifact
      uses: actions/upload-artifact@v4
      with:
        name: SBOM
        path: domoticz/${{ env.SBOM_FILENAME }}

    
  SCA:
    needs: build
    runs-on: 'ubuntu-latest'
    outputs:
      result_url: ${{ steps.sca_result.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v3
      - name: Download SBOM
        uses: actions/download-artifact@master
        with:
          name: SBOM
          path: .

      - uses: ./.github/actions/sca
        with:
          input_file: ${{ env.SBOM_FILENAME }}
          output_file: sca_result.sarif
        
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v4
        if: always()
        id: sca_result
        with:
          name: sca_result.sarif
          path: sca_result.sarif

  DAST:
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - run: 'echo tipa DAST'

  inspection_comment:
    runs-on: ubuntu-latest
    needs:
    - SCA
    - DAST
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Results of Domoticz inspection
      - name: Post the result of inspection
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ### Results of Domoticz inspection
            **Please, familiarize yourself with them**
            - Docker image: `${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}`
            - [SCA inspection result](${{ needs.SCA.outputs.result_url }})
            - [DAST inspection result]()
